1. Импортируйте пакет numpy под именем np

In [3]:
import numpy as np

2. Распечатайте версию numpy

In [2]:
print(np.__version__)

1.26.4


3. Создайте вектор со значениями от 10 до 49 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
vector = np.arange(10, 50, 1)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Перевернуть вектор (первый элемент становится последним)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [9]:
vector = np.flip(vector)
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [12]:
A = np.random.random((5,5))
print(A)

[[0.64358985 0.77621004 0.68329018 0.91774474 0.91328176]
 [0.21473351 0.63715337 0.92090262 0.7721383  0.26861897]
 [0.49428744 0.85288126 0.17350766 0.7782993  0.3882513 ]
 [0.8929048  0.81732248 0.71134781 0.1656408  0.91518786]
 [0.08368765 0.15504735 0.43085952 0.99051854 0.85670333]]


In [21]:
A = np.random.random((5,5))
print(A)
np.mean(A, axis=1)
np.median(A, axis=1)

[[0.60513139 0.51104551 0.13604523 0.33484451 0.51645653]
 [0.392631   0.09547926 0.97606903 0.61395921 0.16547982]
 [0.54267571 0.57232109 0.94615186 0.93101425 0.57500688]
 [0.98753851 0.72957486 0.55068127 0.56205486 0.14015957]
 [0.10731879 0.09344145 0.44873276 0.80195026 0.64184683]]


array([0.51104551, 0.392631  , 0.57500688, 0.56205486, 0.44873276])

array([0.77621004, 0.63715337, 0.49428744, 0.81732248, 0.43085952])

6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [ ]:
a = np.array([x for x in range(27)])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [23]:
a = np.array([x for x in range(27)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [26]:
a = a.reshape(3, 3, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [40]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [36]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

[[ True False False]
 [ True  True  True]
 [False False  True]]


In [60]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]]) 
b = a.astype(bool)
b

array([[ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

In [41]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]]) 
a = np.array(a, dtype=bool)
a

array([[ True, False, False],
       [ True,  True,  True],
       [False, False,  True]])

9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [82]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [83]:
a3 = np.hstack((a1, a2))
a3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [84]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [10 11]]


In [86]:
a3 = np.vstack((a1, a2))
a3

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [90]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

(array([0, 3, 4], dtype=int64),)


In [92]:
np.where(a == b)

(array([0, 3, 4], dtype=int64),)

12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [93]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [94]:
c = a @ b
c

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

13. Выведите транспонированную матрицу

In [95]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [96]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [102]:
angles = np.array([3.14, 3.14/2, 6.28])
angles

array([3.14, 1.57, 6.28])

[ 0.00159265  0.99999968 -0.0031853 ]


In [103]:
angles = np.sin(angles)
angles

array([ 0.00159265,  0.99999968, -0.0031853 ])

15. Отсортировать вектор

In [104]:
v = np.random.random(size=[10])
print(v)

[0.79430661 0.88250267 0.80222315 0.68796623 0.19517161 0.35271915
 0.11282773 0.07870859 0.78939144 0.90958312]


[0.13178341 0.14962622 0.26204075 0.30821184 0.34446024 0.45199466
 0.51581108 0.79408365 0.87313982 0.88810901]


In [106]:
v.sort()
v

array([0.07870859, 0.11282773, 0.19517161, 0.35271915, 0.68796623,
       0.78939144, 0.79430661, 0.80222315, 0.88250267, 0.90958312])

16. Проверить, одинаковы ли два NumPy массива

In [107]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

True


In [110]:
np.array_equal(a, b)

True

17. В одномерном массиве заменить максимальный элемент на ноль

In [73]:
Z = np.random.random(10)

In [74]:
Z

array([0.16782157, 0.13655578, 0.59454878, 0.02957322, 0.81242629,
       0.71645444, 0.48757387, 0.05812814, 0.21499663, 0.24011352])

[0.16782157 0.13655578 0.59454878 0.02957322 0.         0.71645444
 0.48757387 0.05812814 0.21499663 0.24011352]


In [115]:
Z = np.random.random(10)
Z

array([0.44526267, 0.69298096, 0.03696063, 0.23227657, 0.58034151,
       0.60527594, 0.71964568, 0.84753999, 0.04767467, 0.42576817])

In [116]:
index = Z.argmax()
Z[index] = 0
Z

array([0.44526267, 0.69298096, 0.03696063, 0.23227657, 0.58034151,
       0.60527594, 0.71964568, 0.        , 0.04767467, 0.42576817])

18. Замените все нечетные числа одномерного массива на -1.

In [76]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [13]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[1::2] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [23]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])
arr

array([ 0,  1, 20,  3,  4,  5,  6, -7,  8, 90])

In [90]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

In [29]:
arr[arr < 5] = 10
arr[arr > 30] = 10
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [37]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])


array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])

In [33]:
np.sort(a, axis=0)

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])